AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy required components for StackSet custom resources in this region.  Lambda
  ARN is exported as StackSetCustomResource
Outputs:
  StackSetFunctionArn:
    Description: Resource ARN for the StackSetCustom resource Lambda function
    Export:
      Name: StackSetCustomResource
    Value:
      Fn::GetAtt:
      - StackSetResourceFunction
      - Arn
Parameters:
  ModuleName:
    Default: lambda_function
    Type: String
Resources:
  StackSetResourceFunction:
    Properties:
      Code:
        S3Bucket: stackset-resource-888049286042-us-east-2
        S3Key: artifacts/33a881955d2bf269e77fafb3996ed269
      Handler:
        Fn::Sub: ${ModuleName}.handler
      Role:
        Fn::GetAtt:
        - StackSetResourceRole
        - Arn
      Runtime: python3.6
      Timeout: 300
    Type: AWS::Lambda::Function
  StackSetResourceLogGroup:
    DependsOn: StackSetResourceFunction
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackSetResourceFunction}
      RetentionInDays: 7
    Type: AWS::Logs::LogGroup
  StackSetResourceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: cloudformation:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: CloudFormationPermissions
      - PolicyDocument:
          Statement:
          - Action: logs:CreateLogGroup
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*
          Version: '2012-10-17'
        PolicyName: LambdaPermissions
      - PolicyDocument:
          Statement:
          - Action:
            - s3:Get*
            - s3:List*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: S3Permissions
    Type: AWS::IAM::Role
